{
 "title": "(Draft) Resources Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(up, job)" } },
   {
    "name": "alias",
    "label": "Device",
    "query": {
     "query": "label_values({job=~\"$job\"}, alias)"
    }
   },
   {
    "name": "cpu",
    "label": "CPU Core",
    "query": {
     "query": "label_values({job=~\"$job\"}, cpu)"
    }
   },
   {
    "name": "disk_partition",
    "label": "Disk Partition",
    "query": {
     "query": "label_values({job=~\"$job\"}, disk_partition)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Disk I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top Read Throughput",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, rate(diskio_read{job=~\"$job\", alias=~\"$alias\", disk_partition=~\"$disk_partition\"}[5m]))",
     "legendFormat": "{{alias}}-{{disk_partition}}-Read"
    }
   ]
  },
  {
   "title": "Top Write Throughput",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, rate(diskio_write{job=~\"$job\", alias=~\"$alias\", disk_partition=~\"$disk_partition\"}[5m]))",
     "legendFormat": "{{alias}}-{{disk_partition}}-Write"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "User Load",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cpu_user_load{job=~\"$job\", alias=~\"$alias\", cpu=~\"$cpu\"}",
       "legendFormat": "{{alias}}-{{cpu}}"
      }
     ]
    },
    {
     "title": "System Load",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cpu_system_load{job=~\"$job\", alias=~\"$alias\", cpu=~\"$cpu\"}",
       "legendFormat": "{{alias}}-{{cpu}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * (\n  (memory_current{job=~\"$job\", alias=~\"$alias\"})\n  /\n  on(alias, job)\n  memory_max{job=~\"$job\", alias=~\"$alias\"}\n)\n",
       "legendFormat": "{{alias}} {{name}}"
      }
     ]
    },
    {
     "title": "Swap Usage",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * (\n  memory_swap_current{job=~\"$job\", alias=~\"$alias\"}\n  /\n  on(alias, job)\n  memory_swap_max{job=~\"$job\", alias=~\"$alias\"}\n)\n",
       "legendFormat": "{{alias}} {{name}}"
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "memory_current{job=~\"$job\", alias=~\"$alias\"}",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "memory_max{job=~\"$job\", alias=~\"$alias\"}",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "memory_swap_current{job=~\"$job\", alias=~\"$alias\"}",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "memory_swap_max{job=~\"$job\", alias=~\"$alias\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disks (Physical Devices Only)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Free",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 10, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * (physical_disk_free{job=\"$job\", alias=\"$alias\", disk_partition=\"$disk_partition\"} / \non (job, alias, disk_partition)\nphysical_disk_total{job=\"$job\", alias=\"$alias\", disk_partition=\"$disk_partition\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 6, "x": 10, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * (1- (physical_disk_free{job=\"$job\", alias=\"$alias\", disk_partition=\"$disk_partition\"} / \non(job, alias, disk_partition) \nphysical_disk_total{job=\"$job\", alias=\"$alias\", disk_partition=\"$disk_partition\"}))",
       "legendFormat": "{{alias}}-{{disk_partition}}-Used"
      },
      {
       "expr": "100 * ((physical_disk_free{job=\"$job\", alias=\"$alias\", disk_partition=\"$disk_partition\"} / \non(job, alias, disk_partition) \nphysical_disk_total{job=\"$job\", alias=\"$alias\", disk_partition=\"$disk_partition\"}))",
       "legendFormat": "{{alias}}-{{disk_partition}}-Free"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "physical_disk_inodes_free{job=\"$job\", alias=\"$alias\", disk_partition=\"$disk_partition\"}",
       "legendFormat": "{{alias}}-{{disk_partition}}"
      }
     ]
    },
    {
     "title": "Time to Full Disk",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(physical_disk_free{job=\"$job\", alias=\"$alias\", disk_partition=\"$disk_partition\"}) /\n(-1 * deriv(physical_disk_free{job=\"$job\", alias=\"$alias\", disk_partition=\"$disk_partition\"}[72h]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Trends Over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "CPU Load Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "cpu_user_load{job=~\"$job\", alias=~\"$alias\", cpu=~\"$cpu\"}",
     "legendFormat": "{{alias}} - User Load"
    },
    {
     "expr": "cpu_system_load{job=~\"$job\", alias=~\"$alias\", cpu=~\"$cpu\"}",
     "legendFormat": "{{alias}} - System Load"
    },
    {
     "expr": "cpu_idle{job=~\"$job\", alias=~\"$alias\", cpu=~\"$cpu\"}",
     "legendFormat": "{{alias}} - Idle"
    }
   ]
  },
  {
   "title": "Memories Over Time (B)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "memory_current{job=~\"$job\", alias=~\"$alias\"}",
     "legendFormat": "{{alias}} - Memory {{name}}"
    },
    {
     "expr": "memory_swap_current{job=~\"$job\", alias=~\"$alias\"}",
     "legendFormat": "{{alias}} - Swap {{name}}"
    }
   ]
  },
  {
   "title": "Memories Over Time (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (\n  (memory_current{job=~\"$job\", alias=~\"$alias\"})\n  /\n  on(alias, job)\n  memory_max{job=~\"$job\", alias=~\"$alias\"}\n)\n",
     "legendFormat": "{{alias}} - Memory {{name}}"
    },
    {
     "expr": "100 * (\n  memory_swap_current{job=~\"$job\", alias=~\"$alias\"}\n  /\n  on(alias, job)\n  memory_swap_max{job=~\"$job\", alias=~\"$alias\"}\n)\n",
     "legendFormat": "{{alias}} - Swap {{name}}"
    }
   ]
  },
  {
   "title": "Disk Free Space (Physical Devices Only)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "physical_disk_free{job=\"$job\", alias=\"$alias\", disk_partition=\"$disk_partition\"}",
     "legendFormat": "{{alias}}-{{disk_partition}}"
    }
   ]
  },
  {
   "title": "Disk Read/Write Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(diskio_read{job=~\"$job\", alias=~\"$alias\", disk_partition=~\"$disk_partition\"}[5m])\n",
     "legendFormat": "{{alias}}-{{disk_partition}}-Read"
    },
    {
     "expr": "rate(diskio_write{job=~\"$job\", alias=~\"$alias\", disk_partition=~\"$disk_partition\"}[5m])\n",
     "legendFormat": "{{alias}}-{{disk_partition}}-Write"
    }
   ]
  }
 ]
}