{
 "title": "(Draft) Resources Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(up, job)" } },
   {
    "name": "alias",
    "label": "Device",
    "query": {
     "query": "label_values({job=~\"$job\"}, alias)"
    }
   },
   {
    "name": "cpu",
    "label": "CPU Core",
    "query": {
     "query": "label_values({job=~\"$job\"}, cpu)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Physical Devices Exclusive Panels",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "User Load",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_user_load{job=~\"$job\", alias=~\"$alias\", cpu=~\"$cpu\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_system_load{job=~\"$job\", alias=~\"$alias\", cpu=~\"$cpu\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\n  (memory_current{job=~\"$job\", alias=~\"$alias\"})\n  /\n  on(alias, job)\n  memory_max{job=~\"$job\", alias=~\"$alias\"}\n)\n",
     "legendFormat": "{{alias}} {{name}}"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\n  memory_swap_current{job=~\"$job\", alias=~\"$alias\"}\n  /\n  on(alias, job)\n  memory_swap_max{job=~\"$job\", alias=~\"$alias\"}\n)\n",
     "legendFormat": "{{alias}} {{name}}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "memory_current{job=~\"$job\", alias=~\"$alias\"}",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "memory_max{job=~\"$job\", alias=~\"$alias\"}",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "memory_swap_current{job=~\"$job\", alias=~\"$alias\"}",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "memory_swap_max{job=~\"$job\", alias=~\"$alias\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  { "title": "Temporal Charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "CPU Load Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "cpu_user_load{job=~\"$job\", alias=~\"$alias\", cpu=~\"$cpu\"}",
     "legendFormat": "{{alias}} - User Load"
    },
    {
     "expr": "cpu_system_load{job=~\"$job\", alias=~\"$alias\", cpu=~\"$cpu\"}",
     "legendFormat": "{{alias}} - System Load"
    },
    {
     "expr": "cpu_idle{job=~\"$job\", alias=~\"$alias\", cpu=~\"$cpu\"}",
     "legendFormat": "{{alias}} - Idle"
    }
   ]
  },
  {
   "title": "Memories Over Time (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (\n  (memory_current{job=~\"$job\", alias=~\"$alias\"})\n  /\n  on(alias, job)\n  memory_max{job=~\"$job\", alias=~\"$alias\"}\n)\n",
     "legendFormat": "{{alias}} - Memory {{name}}"
    },
    {
     "expr": "100 * (\n  memory_swap_current{job=~\"$job\", alias=~\"$alias\"}\n  /\n  on(alias, job)\n  memory_swap_max{job=~\"$job\", alias=~\"$alias\"}\n)\n",
     "legendFormat": "{{alias}} - Swap {{name}}"
    }
   ]
  },
  {
   "title": "Memories Over Time (B)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "memory_current{job=~\"$job\", alias=~\"$alias\"}",
     "legendFormat": "{{alias}} - Memory {{name}}"
    },
    {
     "expr": "memory_swap_current{job=~\"$job\", alias=~\"$alias\"}",
     "legendFormat": "{{alias}} - Swap {{name}}"
    }
   ]
  }
 ]
}