{
 "title": "Resources Monitoring",
 "tags": [
  "resource-monitoring",
  "system-health"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(up, job)" } },
   {
    "name": "alias",
    "label": "Device",
    "query": {
     "query": "label_values({job=~\"$job\"}, alias)"
    }
   },
   {
    "name": "cpu",
    "label": "CPU Core",
    "query": {
     "query": "label_values({job=~\"$job\"}, cpu)"
    }
   },
   {
    "name": "disk_partition",
    "label": "Disk Partition",
    "query": {
     "query": "label_values({job=~\"$job\"}, disk_partition)"
    }
   },
   {
    "name": "interface",
    "label": "Network Interface",
    "query": {
     "query": "label_values({job=~\"$job\"}, interface)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "User Load",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cpu_user_load{job=~\"$job\", alias=~\"$alias\", cpu=~\"$cpu\"}",
       "legendFormat": "{{alias}}-{{cpu}}"
      }
     ]
    },
    {
     "title": "System Load",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cpu_system_load{job=~\"$job\", alias=~\"$alias\", cpu=~\"$cpu\"}",
       "legendFormat": "{{alias}}-{{cpu}}"
      }
     ]
    },
    {
     "title": "Total Load - Physical Devices Only",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(100 - cpu_idle{job=~\"$job\", job!=\"virtual_hosts\", alias=~\"$alias\", cpu=~\"$cpu\"})\nor\nabsent(cpu_idle{job=~\"$job\", job!=\"virtual_hosts\", alias=~\"$alias\", cpu=~\"$cpu\"}) * 0",
       "legendFormat": "{{alias}}-{{cpu}}"
      }
     ]
    },
    {
     "title": "Other Load - Physical Devices Only",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "# (100 - cpu_idle{job=~\"$job\", alias=~\"$alias\", cpu=~\"$cpu\"}) - (cpu_system_load{job=~\"$job\", alias=~\"$alias\", cpu=~\"$cpu\"} + cpu_user_load{job=~\"$job\", alias=~\"$alias\", cpu=~\"$cpu\"})\n\n(\n  (\n    (100 - cpu_idle{job=~\"$job\", job!=\"virtual_hosts\", alias=~\"$alias\", cpu=~\"$cpu\"})\n    or\n    (absent(cpu_idle{job=~\"$job\", job!=\"virtual_hosts\", alias=~\"$alias\", cpu=~\"$cpu\"}) * 0)\n  )\n  -\n  (\n    cpu_system_load{job=~\"$job\", alias=~\"$alias\", cpu=~\"$cpu\"} +\n    cpu_user_load{job=~\"$job\", alias=~\"$alias\", cpu=~\"$cpu\"}\n  )\n)\nor\nabsent(cpu_idle{job=~\"$job\", job!=\"virtual_hosts\", alias=~\"$alias\", cpu=~\"$cpu\"}) * 0\n",
       "legendFormat": "{{alias}}-{{cpu}}"
      }
     ]
    },
    {
     "title": "I/O Wait - Physical Devices Only",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "physical_cpu_usage_iowait{job=~\"$job\", alias=~\"$alias\", cpu=~\"$cpu\"}",
       "legendFormat": "{{alias}}-{{cpu}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Load",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 380 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * (\n  (memory_current{job=~\"$job\", alias=~\"$alias\"})\n  /\n  on(alias, job)\n  memory_max{job=~\"$job\", alias=~\"$alias\"}\n)\n",
       "legendFormat": "{{alias}} {{name}}"
      }
     ]
    },
    {
     "title": "Swap Load",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 380 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * (\n  memory_swap_current{job=~\"$job\", alias=~\"$alias\"}\n  /\n  on(alias, job)\n  memory_swap_max{job=~\"$job\", alias=~\"$alias\"}\n)\n",
       "legendFormat": "{{alias}} {{name}}"
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 380 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "memory_current{job=~\"$job\", alias=~\"$alias\"}",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "memory_max{job=~\"$job\", alias=~\"$alias\"}",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "memory_swap_current{job=~\"$job\", alias=~\"$alias\"}",
       "legendFormat": "{{alias}}"
      },
      {
       "expr": "memory_swap_max{job=~\"$job\", alias=~\"$alias\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disks (Physical Devices Only)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Free",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 10, "x": 0, "y": 381 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * (\n  physical_disk_free{job=\"$job\", alias=\"$alias\", disk_partition=~\"$disk_partition\"} /\n  on (job, alias, disk_partition)\n  physical_disk_total{job=\"$job\", alias=\"$alias\", disk_partition=~\"$disk_partition\"}\n)\n",
       "legendFormat": "{{alias}}-{{disk_partition}}"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 6, "x": 10, "y": 381 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * (1 - (\n  physical_disk_free{job=\"$job\", alias=\"$alias\", disk_partition=~\"$disk_partition\"} /\n  on (job, alias, disk_partition)\n  physical_disk_total{job=\"$job\", alias=\"$alias\", disk_partition=~\"$disk_partition\"}\n))\n",
       "legendFormat": "{{alias}}-{{disk_partition}}-Used"
      },
      {
       "expr": "100 * (\n  physical_disk_free{job=\"$job\", alias=\"$alias\", disk_partition=~\"$disk_partition\"} /\n  on (job, alias, disk_partition)\n  physical_disk_total{job=\"$job\", alias=\"$alias\", disk_partition=~\"$disk_partition\"}\n)\n",
       "legendFormat": "{{alias}}-{{disk_partition}}-Free"
      }
     ]
    },
    {
     "title": "Free Inodes",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 381 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "physical_disk_inodes_free{job=~\"$job\", alias=~\"$alias\", disk_partition=~\"$disk_partition\"}",
       "legendFormat": "{{alias}}-{{disk_partition}}"
      }
     ]
    },
    {
     "title": "Time to Full Disk",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 386 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "clamp_min((physical_disk_free{job=~\"$job\", alias=~\"$alias\", disk_partition=~\"$disk_partition\"}) /\n(-1 * deriv(physical_disk_free{job=~\"$job\", alias=~\"$alias\", disk_partition=~\"$disk_partition\"}[24h])), 0)",
       "legendFormat": "{{alias}}-{{disk_partition}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk I/O (Alpine Devices Unavailable)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read Throughput",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1017 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(diskio_read{job=~\"$job\", alias=~\"$alias\", disk_partition=~\"$disk_partition\"}[$__range]) > 0",
       "legendFormat": "{{alias}}-{{disk_partition}}-Read"
      }
     ]
    },
    {
     "title": "Write Throughput",
     "type": "stat",
     "gridPos": { "h": 8, "w": 7, "x": 5, "y": 1017 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(diskio_write{job=~\"$job\", alias=~\"$alias\", disk_partition=~\"$disk_partition\"}[$__range]) > 0",
       "legendFormat": "{{alias}}-{{disk_partition}}-Write"
      }
     ]
    },
    {
     "title": "I/O Utilization - Physical Devices Only",
     "type": "gauge",
     "description": "How busy the partition is",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1017 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "physical_diskio_io_util{job=~\"$job\", alias=~\"$alias\", disk_partition=~\"$disk_partition\"} > 0",
       "legendFormat": "{{alias}}-{{disk_partition}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic Rates",
     "type": "stat",
     "gridPos": { "h": 14, "w": 4, "x": 0, "y": 603 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(net_bytes_recv{job=~\"$job\", alias=~\"$alias\", interface=~\"$interface\"}[$__interval]) * 8",
       "legendFormat": "{{alias}}-{{interface}}-Inbound"
      },
      {
       "expr": "rate(net_bytes_sent{job=~\"$job\", alias=~\"$alias\", interface=~\"$interface\"}[$__interval]) * 8",
       "legendFormat": "{{alias}}-{{interface}}-Outbound"
      }
     ]
    },
    {
     "title": "Network Traffic (Cumulative)",
     "type": "stat",
     "gridPos": { "h": 14, "w": 4, "x": 4, "y": 603 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(net_bytes_recv{job=~\"$job\", alias=~\"$alias\", interface=~\"$interface\"}[$__range])",
       "legendFormat": "{{alias}}-{{interface}}-Inbound"
      },
      {
       "expr": "increase(net_bytes_sent{job=~\"$job\", alias=~\"$alias\", interface=~\"$interface\"}[$__range])",
       "legendFormat": "{{alias}}-{{interface}}-Outbound"
      }
     ]
    },
    {
     "title": "Dropped Rate Over Time",
     "type": "stat",
     "gridPos": { "h": 14, "w": 4, "x": 8, "y": 603 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(net_drop_in{job=~\"$job\", alias=~\"$alias\", interface=~\"$interface\"}[$__interval])",
       "legendFormat": "{{alias}}-{{interface}}-Inbound"
      },
      {
       "expr": "rate(net_drop_out{job=~\"$job\", alias=~\"$alias\", interface=~\"$interface\"}[$__interval])",
       "legendFormat": "{{alias}}-{{interface}}-Outbound"
      }
     ]
    },
    {
     "title": "Errors Over Time",
     "type": "stat",
     "gridPos": { "h": 14, "w": 4, "x": 12, "y": 603 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(net_err_in{job=~\"$job\", alias=~\"$alias\", interface=~\"$interface\"}[$__interval])",
       "legendFormat": "{{alias}}-{{interface}}-Inbound"
      },
      {
       "expr": "rate(net_err_out{job=~\"$job\", alias=~\"$alias\", interface=~\"$interface\"}[$__interval])",
       "legendFormat": "{{alias}}-{{interface}}-Outbound"
      }
     ]
    },
    {
     "title": "Drop Rates",
     "type": "bargauge",
     "gridPos": { "h": 14, "w": 4, "x": 16, "y": 603 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * (rate(net_drop_in{job=~\"$job\", alias=~\"$alias\", interface=~\"$interface\"}[$__interval]) / \n    on (job, alias, interface)\n\n (\n rate(net_drop_in{job=~\"$job\", alias=~\"$alias\", interface=~\"$interface\"}[$__interval])\n + \n rate(net_packets_recv{job=~\"$job\", alias=~\"$alias\", interface=~\"$interface\"}[$__interval])\n )\n )",
       "legendFormat": "{{alias}}-{{interface}}-Inbound"
      },
      {
       "expr": "100 * (rate(net_drop_out{job=~\"$job\", alias=~\"$alias\", interface=~\"$interface\"}[$__interval]) / \n    on (job, alias, interface)\n\n (\n rate(net_drop_out{job=~\"$job\", alias=~\"$alias\", interface=~\"$interface\"}[$__interval])\n + \n rate(net_packets_sent{job=~\"$job\", alias=~\"$alias\", interface=~\"$interface\"}[$__interval])\n )\n )",
       "legendFormat": "{{alias}}-{{interface}}-Outbound"
      }
     ]
    },
    {
     "title": "Error Rates",
     "type": "bargauge",
     "gridPos": { "h": 14, "w": 4, "x": 20, "y": 603 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * (rate(net_err_in{job=~\"$job\", alias=~\"$alias\", interface=~\"$interface\"}[$__interval]) / \n    on (job, alias, interface)\n\n (\n rate(net_err_in{job=~\"$job\", alias=~\"$alias\", interface=~\"$interface\"}[$__interval])\n + \n rate(net_packets_recv{job=~\"$job\", alias=~\"$alias\", interface=~\"$interface\"}[$__interval])\n )\n )",
       "legendFormat": "{{alias}}-{{interface}}-Inbound"
      },
      {
       "expr": "100 * (rate(net_err_out{job=~\"$job\", alias=~\"$alias\", interface=~\"$interface\"}[$__interval]) / \n    on (job, alias, interface)\n\n (\n rate(net_err_out{job=~\"$job\", alias=~\"$alias\", interface=~\"$interface\"}[$__interval])\n + \n rate(net_packets_sent{job=~\"$job\", alias=~\"$alias\", interface=~\"$interface\"}[$__interval])\n )\n )",
       "legendFormat": "{{alias}}-{{interface}}-Outbound"
      }
     ]
    },
    {
     "title": "Summary",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 671 },
     "targets": [
      {
       "expr": "rate(net_err_in{job=~\"$job\", alias=~\"$alias\", interface=~\"$interface\"}[$__interval])",
       "legendFormat": "{{alias}}-{{interface}}-Inbound"
      },
      {
       "expr": "rate(net_err_out{job=~\"$job\", alias=~\"$alias\", interface=~\"$interface\"}[$__interval])",
       "legendFormat": "{{alias}}-{{interface}}-Outbound"
      },
      {
       "expr": "rate(net_drop_in{job=~\"$job\", alias=~\"$alias\", interface=~\"$interface\"}[$__interval])",
       "legendFormat": "{{alias}}-{{interface}}-Outbound"
      },
      {
       "expr": "rate(net_drop_out{job=~\"$job\", alias=~\"$alias\", interface=~\"$interface\"}[$__interval])",
       "legendFormat": "{{alias}}-{{interface}}-Outbound"
      },
      {
       "expr": "rate(net_bytes_recv{job=~\"$job\", alias=~\"$alias\", interface=~\"$interface\"}[$__interval]) * 8 / 1000000",
       "legendFormat": "{{alias}}-{{interface}}-Outbound"
      },
      {
       "expr": "rate(net_bytes_sent{job=~\"$job\", alias=~\"$alias\", interface=~\"$interface\"}[$__interval]) * 8 / 1000000",
       "legendFormat": "{{alias}}-{{interface}}-Outbound"
      }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processes",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1019 },
     "targets": [
      {
       "expr": "processes_running{job=~\"$job\", alias=~\"$alias\"}",
       "legendFormat": "{{alias}}-Running"
      },
      {
       "expr": "processes_sleeping{job=~\"$job\", alias=~\"$alias\"}",
       "legendFormat": "{{alias}}-Sleeping"
      },
      {
       "expr": "processes_zombies{job=~\"$job\", alias=~\"$alias\"}",
       "legendFormat": "{{alias}}-Zombies"
      },
      {
       "expr": "processes_total{job=~\"$job\", alias=~\"$alias\"}",
       "legendFormat": "{{alias}}-Total"
      },
      {
       "expr": "processes_total{job=~\"$job\", alias=~\"$alias\"} - (\n  processes_running{job=~\"$job\", alias=~\"$alias\"} +\n  processes_sleeping{job=~\"$job\", alias=~\"$alias\"} +\n  processes_zombies{job=~\"$job\", alias=~\"$alias\"}\n)",
       "legendFormat": "{{alias}}-Other"
      }
     ]
    }
   ]
  },
  {
   "title": "Trends Over Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Load Over Time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 543 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "# 100 - cpu_idle{job=~\"$job\", alias=~\"$alias\", cpu=~\"$cpu\"}\n\n(100 - cpu_idle{job=~\"$job\", job!=\"virtual_hosts\", alias=~\"$alias\", cpu=~\"$cpu\"})\nor\nabsent(cpu_idle{job=~\"$job\", job!=\"virtual_hosts\", alias=~\"$alias\", cpu=~\"$cpu\"}) * 0",
       "legendFormat": "{{alias}} - Total Load"
      },
      {
       "expr": "cpu_user_load{job=~\"$job\", alias=~\"$alias\", cpu=~\"$cpu\"}",
       "legendFormat": "{{alias}} - User Load"
      },
      {
       "expr": "cpu_system_load{job=~\"$job\", alias=~\"$alias\", cpu=~\"$cpu\"}",
       "legendFormat": "{{alias}} - System Load"
      },
      {
       "expr": "# (100 - cpu_idle{job=~\"$job\", alias=~\"$alias\", cpu=~\"$cpu\"}) - (cpu_system_load{job=~\"$job\", alias=~\"$alias\", cpu=~\"$cpu\"} + cpu_user_load{job=~\"$job\", alias=~\"$alias\", cpu=~\"$cpu\"})\n\n(\n  (\n    (100 - cpu_idle{job=~\"$job\", job!=\"virtual_hosts\", alias=~\"$alias\", cpu=~\"$cpu\"})\n    or\n    (absent(cpu_idle{job=~\"$job\", job!=\"virtual_hosts\", alias=~\"$alias\", cpu=~\"$cpu\"}) * 0)\n  )\n  -\n  (\n    cpu_system_load{job=~\"$job\", alias=~\"$alias\", cpu=~\"$cpu\"} +\n    cpu_user_load{job=~\"$job\", alias=~\"$alias\", cpu=~\"$cpu\"}\n  )\n)\nor\nabsent(cpu_idle{job=~\"$job\", job!=\"virtual_hosts\", alias=~\"$alias\", cpu=~\"$cpu\"}) * 0\n",
       "legendFormat": "{{alias}} - Other"
      }
     ]
    },
    {
     "title": "Memories Over Time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 552 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "memory_current{job=~\"$job\", alias=~\"$alias\"}",
       "legendFormat": "{{alias}} - Memory {{name}}"
      },
      {
       "expr": "memory_swap_current{job=~\"$job\", alias=~\"$alias\"}",
       "legendFormat": "{{alias}} - Swap {{name}}"
      }
     ]
    },
    {
     "title": "Memories Over Time (%)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 552 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * (\n  (memory_current{job=~\"$job\", alias=~\"$alias\"})\n  /\n  on(alias, job)\n  memory_max{job=~\"$job\", alias=~\"$alias\"}\n)\n",
       "legendFormat": "{{alias}} - Memory {{name}}"
      },
      {
       "expr": "100 * (\n  memory_swap_current{job=~\"$job\", alias=~\"$alias\"}\n  /\n  on(alias, job)\n  memory_swap_max{job=~\"$job\", alias=~\"$alias\"}\n)\n",
       "legendFormat": "{{alias}} - Swap {{name}}"
      }
     ]
    },
    {
     "title": "Disk Free Space (Physical Devices Only)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 561 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "physical_disk_free{job=~\"$job\", alias=~\"$alias\", disk_partition=~\"$disk_partition\"}",
       "legendFormat": "{{alias}}-{{disk_partition}}"
      }
     ]
    },
    {
     "title": "Disk Read/Write Over Time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 561 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(diskio_read{job=~\"$job\", alias=~\"$alias\", disk_partition=~\"$disk_partition\"}[$__interval])",
       "legendFormat": "{{alias}}-{{disk_partition}}-Read"
      },
      {
       "expr": "rate(diskio_write{job=~\"$job\", alias=~\"$alias\", disk_partition=~\"$disk_partition\"}[$__interval])\n",
       "legendFormat": "{{alias}}-{{disk_partition}}-Write"
      }
     ]
    },
    {
     "title": "I/O Over Time - Physical Devices Only",
     "type": "timeseries",
     "description": "How busy the partition is",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 570 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "physical_diskio_io_util{job=~\"$job\", alias=~\"$alias\", disk_partition=~\"$disk_partition\"}",
       "legendFormat": "{{alias}}-{{disk_partition}}"
      }
     ]
    },
    {
     "title": "Processes Over Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 570 },
     "targets": [
      {
       "expr": "processes_running{job=~\"$job\", alias=~\"$alias\"}",
       "legendFormat": "{{alias}}-Running"
      },
      {
       "expr": "processes_sleeping{job=~\"$job\", alias=~\"$alias\"}",
       "legendFormat": "{{alias}}-Sleeping"
      },
      {
       "expr": "processes_zombies{job=~\"$job\", alias=~\"$alias\"}",
       "legendFormat": "{{alias}}-Zombies"
      },
      {
       "expr": "processes_total{job=~\"$job\", alias=~\"$alias\"}",
       "legendFormat": "{{alias}}-Total"
      },
      {
       "expr": "processes_total{job=~\"$job\", alias=~\"$alias\"} - (\n  processes_running{job=~\"$job\", alias=~\"$alias\"} +\n  processes_sleeping{job=~\"$job\", alias=~\"$alias\"} +\n  processes_zombies{job=~\"$job\", alias=~\"$alias\"}\n)",
       "legendFormat": "{{alias}}-Other"
      }
     ]
    },
    {
     "title": "Network Traffic Rates",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 578 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(net_bytes_recv{job=~\"$job\", alias=~\"$alias\", interface=~\"$interface\"}[$__interval]) * 8",
       "legendFormat": "{{alias}}-{{interface}}-Inbound"
      },
      {
       "expr": "rate(net_bytes_sent{job=~\"$job\", alias=~\"$alias\", interface=~\"$interface\"}[$__interval]) * 8",
       "legendFormat": "{{alias}}-{{interface}}-Outbound"
      }
     ]
    },
    {
     "title": "Network Traffic (Cumulative)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 578 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "increase(net_bytes_recv{job=~\"$job\", alias=~\"$alias\", interface=~\"$interface\"}[$__range])",
       "legendFormat": "{{alias}}-{{interface}}-Inbound"
      },
      {
       "expr": "increase(net_bytes_sent{job=~\"$job\", alias=~\"$alias\", interface=~\"$interface\"}[$__range])",
       "legendFormat": "{{alias}}-{{interface}}-Outbound"
      }
     ]
    },
    {
     "title": "Network Dropped Packets Over Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 587 },
     "targets": [
      {
       "expr": "rate(net_drop_in{job=~\"$job\", alias=~\"$alias\", interface=~\"$interface\"}[$__interval])",
       "legendFormat": "{{alias}}-{{interface}}-Inbound"
      },
      {
       "expr": "rate(net_drop_out{job=~\"$job\", alias=~\"$alias\", interface=~\"$interface\"}[$__interval])",
       "legendFormat": "{{alias}}-{{interface}}-Outbound"
      }
     ]
    },
    {
     "title": "Network Errors Over Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 587 },
     "targets": [
      {
       "expr": "rate(net_err_in{job=~\"$job\", alias=~\"$alias\", interface=~\"$interface\"}[$__interval])",
       "legendFormat": "{{alias}}-{{interface}}-Inbound"
      },
      {
       "expr": "rate(net_err_out{job=~\"$job\", alias=~\"$alias\", interface=~\"$interface\"}[$__interval])",
       "legendFormat": "{{alias}}-{{interface}}-Outbound"
      }
     ]
    }
   ]
  }
 ]
}